version: '3'
services:
  feedback:
    build: .
    image: esignbr/wildfly-mysql
    container_name: wildfly
    restart: always
    env_file:
      - mysql.env
    ports:
      - 8080:8080
    depends_on:
      - mysql
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    env_file:
      - mysql.env
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
