version: '3'
services:
  feedback:
    build: .
    image: esignbr/wildfly-mysql
    container_name: wildfly
    env_file:
      - mysql.env
    ports:
      - 8080:8080
    depends_on:
      - mysql
  mysql:
    image: mysql:8
    container_name: mysql
    env_file:
      - mysql.env
